require:
  - rubocop-rails
  - rubocop-rspec
  - ./rubocop/rubocop

AllCops:
  NewCops: enable
  Exclude:
    - vendor/**/*
    - .circleci/*
    - db/schema.rb
    - bin/bundle
    - rubocop/**/*.rb

Layout/LineLength:
  Max: 100
  AllowURI: true
  URISchemes:
    - http
    - https
  Exclude:
    - config/**/*

Metrics/AbcSize:
  Max: 15
  Exclude:
    - db/migrate/*
    - app/channels/graphql_channel.rb

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - config/**/*
    - spec/**/*
    - lib/tasks/auto_annotate_models.rake

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false
  Max: 200

Metrics/CyclomaticComplexity:
  Max: 6

Metrics/MethodLength:
  CountComments: false
  Max: 24

Metrics/ModuleLength:
  CountComments: false
  Max: 200

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Style/BlockDelimiters:
  EnforcedStyle: braces_for_chaining

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# Rails Cops

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/**/**

Rails/NotNullColumn:
  Enabled: false

Rails/RakeEnvironment:
  Exclude:
    - lib/tasks/auto_annotate_models.rake
    - lib/tasks/linters.rake
