default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['DB_HOST'] %>
  pool: 5
  timeout: 5000
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>

development:
  <<: *default
  database: <%= "rails-graphql-api-boilerplate-development" %>

test:
  <<: *default
  database: <%= "rails-graphql-api-boilerplate-test" %>
