name: Tests and Linters

on:
  pull_request:
    branches:
      - 'master'
      - 'develop'
  push:
    branches:
      - 'master'
      - 'develop'
      - /^release.*/

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby (.ruby-version)
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true

    - name: Install PostgreSQL 11 client
      run: sudo apt-get -yqq install libpq-dev

    - name: Build App
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: |
        gem install bundler
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bin/rails db:setup

    - name: Run Linters
      run: |
        git fetch origin master:refs/remotes/origin/master
        bundle exec rake linters

    - name: Run Tests
      env:
        PGHOST: localhost
        PGUSER: postgres
        RAILS_ENV: test
      run: bundle exec rspec
